# NUMPY ARRAY

**INTRODUCTION TO NUMPY ARRAY**

In [1]:
import numpy as np

In [2]:
import sklearn


**1-D ARRAY**

In [3]:
A = np.array([12, 5, 43, 22, 10]  , np.int64)

In [4]:
A

array([12,  5, 43, 22, 10], dtype=int64)

In [5]:
A[0]

12

**2-D array**

In [6]:
A1 = np.array([[10, 21, 34, 56, 89]], np.int64)

In [7]:
A1[0][0]

10

In [8]:
A1[0]

array([10, 21, 34, 56, 89], dtype=int64)

In [9]:
A1.shape


(1, 5)

In [10]:
A1.dtype

dtype('int64')

**ARRAY CREATION** 
*https://numpy.org/doc/stable/user/basics.creation.html*

**Conversion from other Python structures**

In [11]:
listA1 = np.array([[12,10,21], [24,43, 56], [3, 6, 4]])

In [12]:
listA1

array([[12, 10, 21],
       [24, 43, 56],
       [ 3,  6,  4]])

In [13]:
listA1.shape

(3, 3)

In [14]:
listA1.size


9

In [15]:
listA1.dtype

dtype('int32')

In [16]:
zeros = np.zeros((2, 5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.shape, zeros.size


((2, 5), 10)

In [19]:
range = np.arange(12)

In [20]:
range


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
linspace = np.linspace(1, 8, 4)

In [22]:
linspace

array([1.        , 3.33333333, 5.66666667, 8.        ])

In [23]:
emp= np.empty((2,5))

In [24]:
emp


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
emp_like = np.empty_like(linspace)

In [26]:
emp_like

array([1.        , 3.33333333, 5.66666667, 8.        ])

In [27]:
idt = np.identity(45)

In [28]:
idt

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
idt.shape

(45, 45)

In [30]:
ar = np.arange(20)

In [31]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
ar.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
ar = ar.ravel()

In [34]:
ar.shape

(20,)

In [35]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
x =[[2,4,6], [5, 3, 7] , [9, 5, 8]]

In [37]:
ara = np.array(x)

In [38]:
ara

array([[2, 4, 6],
       [5, 3, 7],
       [9, 5, 8]])

In [39]:
ara.sum(axis = 0) #it gives summation of column elements

array([16, 12, 21])

In [40]:
ara.sum(axis = 1) #it gives summation of row elements

array([12, 15, 22])

In [41]:
ara.T #transpose of a array

array([[2, 5, 9],
       [4, 3, 5],
       [6, 7, 8]])

In [42]:
for item in ara.flat :
    print(item)

2
4
6
5
3
7
9
5
8


In [43]:
ara.ndim #to print dimesnion of an array

2

In [44]:
ara.nbytes

36

In [45]:
one = ara.ravel()

In [46]:
one

array([2, 4, 6, 5, 3, 7, 9, 5, 8])

In [47]:
one.argmax() #to print the index of largest element

6

In [48]:
one.argmin() #to print the index of smallest element

0

In [49]:
one.argsort() #to print the index of the sorted array

array([0, 4, 1, 3, 7, 2, 5, 8, 6], dtype=int64)

In [50]:
listA1 =A1.ravel()

In [51]:
listA1.argmax()

4

In [52]:
listA1.argmin()

0

In [53]:
listA1.argmax(axis = 0)

4

In [54]:
listA1.argmin(axis = 0)

0

In [55]:
listA1.argsort(axis = 0)

array([0, 1, 2, 3, 4], dtype=int64)

In [56]:
x1 = [[ 0,  1,  2,  3,  4],    #it is a list 
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]

In [57]:
x2 = [[ 2,  3,  1,  7,  5],    #it is a list 
       [3,  0,  4,  6,  2],
       [9,  8,  7,  6, 23],
       [1,  6,  7,  1,  9]]

In [58]:
x1 + x2     #basically we are adding lists

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [2, 3, 1, 7, 5],
 [3, 0, 4, 6, 2],
 [9, 8, 7, 6, 23],
 [1, 6, 7, 1, 9]]

In [59]:
x3 = np.array(x1)
x4 = np.array(x2)
 

In [60]:
#addition of sum of corresponding elements of list1 and list2

x3+x4

array([[ 2,  4,  3, 10,  9],
       [ 8,  6, 11, 14, 11],
       [19, 19, 19, 19, 37],
       [16, 22, 24, 19, 28]])

In [61]:
x3.sum() #sum of all elements of array x3

190

In [62]:
x3.max(), x3.min() #printing maximum and minimum elements in array x3

(19, 0)

In [63]:
x3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [64]:
np.where(x3>10)

(array([2, 2, 2, 2, 3, 3, 3, 3, 3], dtype=int64),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [65]:
listA1

array([10, 21, 34, 56, 89], dtype=int64)

In [66]:
np.where(listA1>10)

(array([1, 2, 3, 4], dtype=int64),)

In [67]:
np.count_nonzero(x3)

19

In [68]:
np.nonzero(x3)

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3],
       dtype=int64),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       dtype=int64))

**PROGRAMS ON NUMPY ARRAY**

In [69]:
import numpy as np
A1 = np.array([[12, 23,  34],
              [21,  32,  4],
              [5,   7,   9]])

In [70]:
A1

array([[12, 23, 34],
       [21, 32,  4],
       [ 5,  7,  9]])

In [71]:
A2 = np.array([[ 2,  3,  4],                                                             
               [ 5,  6,  7],                                                             
               [ 8,  9,  10]]) 

In [72]:
A2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [73]:
Ad = np.add(A1, A2)
SB = np.subtract(A1, A2)
Ml = np.multiply(A1, A2)
Di = np.divide(A1, A2)
Md = np.mod(A1, A2)
Rr = np.remainder(A1, A2)


print('addition will give : {0}'.format(Ad))
print('subtraction will give : {0}'.format(SB))
print('multiplication will give : {0}'.format(Ml))
print('division will give : {0}'.format(Di))
print('mod will give : {0}'.format(Ad))
print('remainder will give : {0}'.format(Ad))

addition will give : [[14 26 38]
 [26 38 11]
 [13 16 19]]
subtraction will give : [[10 20 30]
 [16 26 -3]
 [-3 -2 -1]]
multiplication will give : [[ 24  69 136]
 [105 192  28]
 [ 40  63  90]]
division will give : [[6.         7.66666667 8.5       ]
 [4.2        5.33333333 0.57142857]
 [0.625      0.77777778 0.9       ]]
mod will give : [[14 26 38]
 [26 38 11]
 [13 16 19]]
remainder will give : [[14 26 38]
 [26 38 11]
 [13 16 19]]


In [74]:
Ac = A1

In [75]:
Ac

array([[12, 23, 34],
       [21, 32,  4],
       [ 5,  7,  9]])

In [76]:
z = np.where(Ac%2 ==0) #to check the position of even numbers

In [77]:
z

(array([0, 0, 1, 1], dtype=int64), array([0, 2, 1, 2], dtype=int64))

In [78]:
np.where(Ac%2 !=0)  #to check the position of odd numbers

(array([0, 1, 2, 2, 2], dtype=int64), array([1, 0, 0, 1, 2], dtype=int64))

In [79]:
#program to count total even and odd numbers in a 1-d array
import numpy as np
Ac = Ac.ravel()
Ac1 = np.array(Ac)
p = Ac.size
print(Ac1)
nE = nO = 0
for i in Ac1 :
    if( i != 0 ):
        if (i % 2 == 0):
            nE = nE + 1
        else:
            nO = nO + 1
    
print("total even numbers are %d and odd are %d" %(nE, nO ))       

[12 23 34 21 32  4  5  7  9]
total even numbers are 4 and odd are 5


In [80]:
A1

array([[12, 23, 34],
       [21, 32,  4],
       [ 5,  7,  9]])

In [81]:
A1.sum()

147

In [82]:
#functions to calculate average of an array
avg = (A1.sum())/A1.size 
#or
#np.average(A1)

In [86]:
#program to print array elements greater than average
avg1 = np.average(Ac1)
for i in Ac1 : 
    if  i > avg :
        print(i)

23
34
21
32


In [87]:
#program to count and tell whether a number is positive, negative, even or odd ?
array  = A1.ravel()

nE = nO = 0
print("even and odd numers in the array are : ")
for i in array :
    if (i % 2 == 0):
        print("%d : even" %i)
        nE = nE + 1
    else:
        nO = nO + 1
        print("%d : odd" %i)

print("total even numbers are %d and odd are %d" %(nE, nO ))       

print("positive and negative numers in the array are : ")
nP = nN = 0
for i in array :
    if (i > 0):
        print("%d : positive" %i)
        nP = nP + 1
    elif (i < 0):
        nN = nN + 1
        print("%d : negative" %i)
    else :
        none
print("total positive numbers are %d and negative are %d" %(nP, nN ))       

even and odd numers in the array are : 
12 : even
23 : odd
34 : even
21 : odd
32 : even
4 : even
5 : odd
7 : odd
9 : odd
total even numbers are 4 and odd are 5
positive and negative numers in the array are : 
12 : positive
23 : positive
34 : positive
21 : positive
32 : positive
4 : positive
5 : positive
7 : positive
9 : positive
total positive numbers are 9 and negative are 0


In [88]:
#program to print array elements in reverse order 
print(A1[::-1])

[[ 5  7  9]
 [21 32  4]
 [12 23 34]]


In [97]:
Ac1

array([ 4,  5,  7,  9, 12, 21, 23, 32, 34])

In [98]:
#program to print values at even indexes in an array
avg1 = np.average(Ac1)
for i in range(Ac1.size) :
    if  (i%2 == 0) :
        print(Ac1[i])

TypeError: 'numpy.ndarray' object is not callable

In [99]:
#program to print values at odd indexes in an array
avg1 = np.average(Ac1)
for t in range(Ac1.size) :
    if  (t%2 != 0) :
        print(Ac1[i])

TypeError: 'numpy.ndarray' object is not callable

In [100]:
np.nonzero(Ac1) #positions of nonzero numers in the array

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)

In [101]:
Ac1

array([ 4,  5,  7,  9, 12, 21, 23, 32, 34])

In [102]:
#program to print second largest of an array
Ac2 = Ac1
Ac2.sort()
print(Ac2[len(Ac2)-2])

32


In [103]:
#program to rotate an array to left by n
Al = np.array([5, 10, 15, 18, 9, 2,  6, 66, 332, 82])

nl = int(input("Enter Position to Left Rotate Array Elements = "))

print('Original Array Elements Before Left Rotating')
print(Al)

Arr = np.concatenate((Al[nl:], Al[:nl]), axis = 0)

print('\nArray Elements After Left Rotating')
print(Arr)

Enter Position to Left Rotate Array Elements = 4
Original Array Elements Before Left Rotating
[  5  10  15  18   9   2   6  66 332  82]

Array Elements After Left Rotating
[  9   2   6  66 332  82   5  10  15  18]


In [104]:
#### program to rotate an array to right by n
Ar = Arr

nr = int(input("Enter Position to Right Rotate Array Elements = "))

print('Array Elements Before Right Rotating')
print(Ar)

arr1 = np.concatenate((Ar[-nr:], Ar[:-nr]), axis = 0)

print('\n Array Elements After Right Rotating')
print(arr1)

Enter Position to Right Rotate Array Elements = 4
Array Elements Before Right Rotating
[  9   2   6  66 332  82   5  10  15  18]

 Array Elements After Right Rotating
[  5  10  15  18   9   2   6  66 332  82]


# Thanks